<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <SelfContained>true</SelfContained>
    <DebugType>embedded</DebugType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <Product>PluginTypedText</Product>
    <BaseOutputPath>G:\Quokka\Quokka\PlugBoard\PluginTypedText</BaseOutputPath>
    <Configurations>Plugin</Configurations>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Optimize>True</Optimize>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quokka\Quokka.csproj"></ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <ContentWithTargetPath Include="settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>settings.json</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>

  <ItemGroup>
    <ContentWithTargetPath Include="Icons By Icons8.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>Icons By Icons8.txt</TargetPath>
    </ContentWithTargetPath>

    <ContentWithTargetPath Include="text.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>text.png</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>

</Project>