<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <Product>PluginTypedText</Product>
    <BaseOutputPath>..\BuildOutput\Quokka\PlugBoard\PluginTypedText</BaseOutputPath>
    <PublishDir>..\BuildOutput\Quokka\PlugBoard\PluginTypedText\Plugin\</PublishDir>
    <Configurations>Plugin</Configurations>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Optimize>True</Optimize>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quokka\Quokka.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime;contentFiles</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
    <Page Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <ContentWithTargetPath Include="settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>settings.json</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>

  <ItemGroup>
    <ContentWithTargetPath Include="Icons By Icons8.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>Icons By Icons8.txt</TargetPath>
    </ContentWithTargetPath>

    <ContentWithTargetPath Include="text.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>text.png</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>

</Project>